[package]
name = "demo_cli"
version = "0.1.0"
edition = "2021"
description = "Demo binary using crates-io-demo-lib-nicu1989 from crates.io"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
crates-io-demo-lib-nicu1989 = "0.1.0"

